apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  # - level: Metadata
  - level: RequestResponse
#    resources:
#      - group: "authentication.k8s.io"
#        resources: ["tokenreviews"]
#    verbs: ["create"]
#    users: ["*"]
#  - level: Metadata
#    resources:
#      - group: ""  # core API group
#        resources: ["pods", "services", "deployments", "nodes"]
#    verbs: ["create", "update", "delete"]
#    users: ["*"]  # Capture all users